language: rust
rust:
    - 1.0.0-beta
    - nightly
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: YFJ1s6xn4Rh3jJZ0z0y63COw1DXvFhMlC5A/6eXYFV1v8Fqsl7DGT7FSVPn+0usS5FmWE3oMFQdTZRluZYv/22G53aIUJpNql37FY96zQfhSFEVp58xGLK+Atw+HczWUFKYAESNYTVS0QpMXqair1HyESi1bMTYfc9e1wz+w8pU=
  - secure: cmKaqYBMc6UzNA7P1vE7zbVoUCqh1fYaEHsXCZqKBl6UlGxBMrh62k7t2VbMtFEuIE/ZhmpgI98WmmYyeYSSV9PrASpfvSPQU7DD+DJAutS8folWn92PwF7RYYQDJhvXvizHbmYbJcKNsvaMCuxfH5HDwSGBBzeMV35EzpA4cO8=
