(function() {var implementors = {};
implementors['sass_rs'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='sass_rs/dispatcher/struct.Dispatcher.html' title='sass_rs::dispatcher::Dispatcher'>Dispatcher</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='sass_rs/sass_context/struct.SassFileContext.html' title='sass_rs::sass_context::SassFileContext'>SassFileContext</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='sass_rs/sass_importer/struct.SassImporter.html' title='sass_rs::sass_importer::SassImporter'>SassImporter</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='sass_rs/sass_value/struct.SassValueBuf.html' title='sass_rs::sass_value::SassValueBuf'>SassValueBuf</a>",];implementors['image'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;W&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='image/png/zlib/struct.ZlibEncoder.html' title='image::png::zlib::ZlibEncoder'>ZlibEncoder</a>&lt;W&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;W&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='image/png/deflate/struct.Deflater.html' title='image::png::deflate::Deflater'>Deflater</a>&lt;W&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
